#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx

# Firewall setting: Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

# Override the default index file served as home page
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

# Redirect to /redirect_me to a youtube video
sudo sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Setup 404 page
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

service nginx start
