#!/usr/bin/env bash
# Configure new nginx server to have a custom header
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '11i\add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx start
