#!/usr/bin/env bash

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers

echo "ENABLED=1" > /etc/default/haproxy

printf %s "global
   log 127.0.0.1 local0 notice
   maxconn 2000
   user haproxy
   group haproxy
defaults
   log     global
   mode    http
   option  httplog
   option  dontlognull
   retries 3
   option redispatch
   timeout connect  5000
   timeout client  10000
   timeout server  10000

   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 35-web-01 34.75.10.160:80 check
   server 35-web-01 35.231.86.187:80 check
" > /etc/haproxy/haproxy.cfg

service haproxy start
